### ISSUE TITLE
Unclear how template files are to be managed.

### ISSUE THREAD

**Issue by jevonearth** [angular-ui/bootstrap-bower#1]
After installing angular-ui-bootstrap-bower into my angular project, it can't find its own template files, resulting in browser errors like;

GET http://localhost:9000/template/tooltip/tooltip-popup.html 404 (Not Found) 

How should users manage template files in this scenario?

**Comment by Thilak8654** [comment]
i have read the above comments, i have included ui-bootstrap-tpls.min.js (of version 1.3.3) so it is showing like datepicker-popup.html template is not found, but if i include the same tpls file of **0.X.X** version ,  i will not get the error. but template is not showing in both of the cases, what is the mistake here.
