### ISSUE TITLE
Bower install referencing ui-bootstrap-tpls.min.js missing templates

### ISSUE THREAD

**Issue by unclejustin** [angular-ui/bootstrap-bower#20]
This doesn't seem to be working for me. I am referencing bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js after installing via bower and I get missing template files errors until I download the template directory from github.

According to this issue https://github.com/angular-ui/bootstrap-bower/issues/9 I should not need to download the templates folder separately.

**Comment by ervbsankar** [comment]
when i deploy my code to production servers, how do i enable caching for browsers?

**Comment by unclejustin** [comment]
@ervbsankar you can't. It's a setting on the user's local machine.
