### ISSUE TITLE
Support for angular 1.3.*

### ISSUE THREAD

**Issue by garciaf** [angular-ui/bootstrap-bower#35]
Hello 
Would it be possible to support angular 1.3. ?
Thanks a lot for your work

**Comment by johnnyreilly** [comment]
@chrisirhc, 

Do you mean that when the [issues](https://github.com/angular-ui/bootstrap/labels/AngularJS%201.3) are resolved you'll then amend the bower.json to support Angular 1.3 officially?

**Comment by karianna** [comment]
I'm not @chrisirhc - but that would be the plan yes.

**Comment by johnnyreilly** [comment]
Thanks @karianna.

**Comment by nschloe** [comment]
Much of the bootstrap functionality works alright with angular 1.3.*, in particular the components we used to use (dropdown menus etc.). The restriction to <1.3.0 make it impossible for our project to move on with bootstrap-js onboard.
While I do share the sentiment that one shouldn't release a software with too many bugs, I would like to encourage the maintainers of this package to drop the dependency on angular <1.3.0 and allow for newer versions as well.
After all, some bugs of <https://github.com/angular-ui/bootstrap/labels/AngularJS%201.3> are virtually stale and it's unclear if they will ever be resolved.

**Comment by alexfalkowski** [comment]
Any movement on this?

**Comment by soee** [comment]
+1

**Comment by karianna** [comment]
Hi all, the maintainers had a meeting last night and we'll be working initially on a 0.12.1 release and then a subsequent 0.13.0 release with the minimum fixes we believe that's required for 1.3 compatibility (that doesn't have blocker issues).  0.13.x releases will then roll out to improve that compatibility.

**Comment by alexfalkowski** [comment]
Thank you :+1:

**Comment by motormuis** [comment]
+1

**Comment by vsevolod** [comment]
+1

**Comment by dsge** [comment]
+1

**Comment by aschulz01** [comment]
+1

**Comment by marcdexet** [comment]
+1 (sorry for duplication)

**Comment by evilaliv3** [comment]
+1

**Comment by blargism** [comment]
Can we have an update on status?  We are now nearly 3 months past the creation date of the issue.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by blargism** [comment]
Thank you for that.  I'll keep an anxious eye on things.

**Comment by nadar** [comment]
+1

**Comment by sebastialonso** [comment]
:+1:

**Comment by Stibbons** [comment]
+1

**Comment by rvanbaalen** [comment]
We're very close to releasing UI Bootstrap 0.13.0 with full AngularJS 1.3 support. Things have been moving pretty fast with some new dedicated maintainers since the beginning of March.

**Comment by rvanbaalen** [comment]
For more details on progress etc check the 0.13.0 milestone and meeting minutes and the roadmap in the wiki:

https://github.com/angular-ui/bootstrap/wiki/Roadmap

**Comment by patbaker82** [comment]
@rvanbaalen Brilliant!

**Comment by kukac7** [comment]
:+1:

**Comment by Sshuichi** [comment]
Any news ?

**Comment by spirospolitis** [comment]
Looking forward to this

**Comment by rvanbaalen** [comment]
@spitospolitis clone and build the current master and you'll have the +/-90% ready 0.13 release.

**Comment by frekele** [comment]
+++1 !!!

**Comment by rvanbaalen** [comment]
@frekele instead of taking the time to add +1's, just check the releases. `0.13` has been out for a while now with full Angular 1.3 support.

**Comment by frekele** [comment]
@rvanbaalen Great! sorry and thanks.
