### ISSUE TITLE
Support installs via NPM

### ISSUE THREAD

**Issue by dansomething** [angular-ui/bootstrap-bower#40]

**Comment by troywarr** [comment]
+1 please.

This would make the repo name a misnomer, so I might suggest either:

1. renaming the repo to something like `bootstrap-packaged`
1. creating another repo named `bootstrap-npm` to house a version containing `package.json` in lieu of `bower.json`

#1 seems preferable as it keep things centralized/DRY.

FWIW, this seems like an increasingly common use case with the rise of the npm/Browserify packaging approach (vs. Bower/RequireJS).

**Comment by Foxandxss** [comment]
Let's continue in #60
