### ISSUE TITLE
The inline datepicker week number is woring

### ISSUE THREAD

**Issue by pangsen** [angular-ui/bootstrap-bower#42]
when I use the date picker in inline model, the week number is wrong in month 2015-01. 

![img_22122014_142102](https://cloud.githubusercontent.com/assets/3021695/5521794/e0ddae2e-89e5-11e4-844e-04365629d556.png)

**Comment by goldcaddy77** [comment]
@pangsen - this is just the compiled bower port of the library.  Your feedback would need to go in the main project: https://github.com/angular-ui/bootstrap
