### ISSUE TITLE
install does not include templates

### ISSUE THREAD

**Issue by mattuuh7** [angular-ui/bootstrap-bower#48]
after the installation, loading the modules failed because cannot find the templates. I did have the `ui-bootstrap-tpls.min.js` included

```
 GET http://127.0.0.1:8000/template/modal/window.html 404 (File not found)
angular.js:10140 Error: [$compile:tpload] Failed to load template: template/modal/window.html
http://errors.angularjs.org/1.2.29-build.590+sha.e81b2f7/$compile/tpload?p0=template%2Fmodal%2Fwindow.html
    at VALIDITY_STATE_PROPERTY (angular.js:78)
    at angular.js:6969
    at angular.js:8187
```

**Comment by goldcaddy77** [comment]
@mattuuh7, did you try referencing the file under `bower_components/angular-bootstrap/ui-bootstrap-tpls.js`?

**Comment by rgnevashev** [comment]
in bower.json :
pls replace "main": ["./ui-bootstrap-tpls.js"], to "main": ["./ui-bootstrap-tpls.js","./ui-bootstrap.js"],
I do not always want to use "overrides"

**Comment by goldcaddy77** [comment]
@rgnevashev - `ui-bootstrap-tpls.js` includes everything in `ui-bootstrap.js` already.

**Comment by rgnevashev** [comment]
ok, thx for helping.

**Comment by goldcaddy77** [comment]
No problem.
