### ISSUE TITLE
Collapse broken in 0.13.0

### ISSUE THREAD

**Issue by NitroInside** [angular-ui/bootstrap-bower#55]
In 0.12.1 'collapse' works well, but in 0.13.0 the transition is lost. The element just hide/shows in a frame. 

In the issue https://github.com/angular-ui/bootstrap/issues/3676 it was said that the module has ngAnimate dependency. Must it be on bower.json?

Thanks!

**Comment by rvanbaalen** [comment]
Dont cross-post issues. All issues should be resported on the main repository. This is an auto-generated repo.

**Comment by rvanbaalen** [comment]
ngAnimate is not a required dependency, only if you want fluid transitions and animations. That's probably the reason why it didn't end up in the default dependency list.
