### ISSUE TITLE
Popover does not work

### ISSUE THREAD

**Issue by jpgarcia** [angular-ui/bootstrap-bower#56]
Check this one https://github.com/angular-ui/bootstrap/issues/3767

**Comment by pkozlowski-opensource** [comment]
@jpgarcia there is not much point in opening duplicate issues....

**Comment by jpgarcia** [comment]
I opened this one just in case the owner of this repo did not see the issue in angular-ui/bootstrap as they are different repos.

Sorry about that!

**Comment by rvanbaalen** [comment]
This repo is auto generated by the original repo.
