### ISSUE TITLE
The code is not separated by module in NPM

### ISSUE THREAD

**Issue by 0xR** [angular-ui/bootstrap-bower#57]
In bower you get a file per component which allows you to include the code you are actually using. When I load angular-ui-bootstrap via npm I only get 4 files which contain all the code. We want to keep our javascript bundle size small and are therefore stuck with bower while we want to replace it with npm.

**Comment by rvanbaalen** [comment]
Please report issues at angular-ui/bootstrap. The contents of this repo are automatically generated when the project is built.
