### ISSUE TITLE
on 0.13.0 Bootstrap modal backdrop doesn't disappear when using angular-ui-bootstrap

### ISSUE THREAD

**Issue by albertpeiro** [angular-ui/bootstrap-bower#59]
I use https://angular-ui.github.io/bootstrap/

If I update bootstrap-bower to 0.13 then the modals backdrop never disappears on closing a modal.

On 0.12.1 this was totally fine.
THis happens on both Bootstrap 3.3.4 and 3.3.5

Let me know if you need further detail

**Comment by rvanbaalen** [comment]
Please dont report issues in the bower repo. Instead go to the original repo to report your issues. And this issue is already reported over there. 

Thanks for understanding.
