### ISSUE TITLE
Dependency on bootstrap.css

### ISSUE THREAD

**Issue by fcagalj** [angular-ui/bootstrap-bower#62]
Maybe is obvious that Angular UI Bootstrap depend on bootstrap.css, but I don't see it is documented anywhere. Users usually think that Angular UI Bootstrap depend on Bootstrap itself, and then add whole Bootstrap with jQuery included, which should be avoided.

Why not add dependency to https://github.com/fyockm/bootstrap-css-only and solve all mess up?

**Comment by icfantv** [comment]
hi @fcagalj, this is well documented [here](https://github.com/angular-ui/bootstrap#installation).
