### ISSUE TITLE
Tag 0.12.2 disappear ?

### ISSUE THREAD

**Issue by adamotte** [angular-ui/bootstrap-bower#69]
In my project, everything was working since 1 year until today when i need to do a fresh install.

My bower.json
```json
{
  "name": "app-name",
  "version": "0.0.0",
  "dependencies": {
    "angular": "1.5.0",
    "angular-resource": "1.5.0",
    "angular-cookies": "1.5.0",
    "angular-sanitize": "1.5.0",
    "angular-animate": "1.5.0",
    "angular-route": "1.5.0",
    "angular-bootstrap": "0.12.2",
    "angular-dynamic-locale": "0.1.30",
    "angular-bootstrap-colorpicker": "3.0.18",
    "ng-file-upload": "6.2.1",
    "angular-bootstrap-toggle-switch": "~0.5.6"
  },
  "devDependencies": {
    "angular-mocks": "1.5.0",
    "angular-scenario": "1.5.0"
  },
  "appPath": "app"
}
```

generate an error 
```error
ENORESTARGET No tag found that was able to satisfy 0.12.2
```

**Comment by pkozlowski-opensource** [comment]
Are you sure it worked correctly before? Since looking at the history of this repo there was no 0.12.2 release: https://github.com/angular-ui/bootstrap-bower/commits/master?page=1

Maybe you've changed Bower version at it changed its resolution strategy?

**Comment by adamotte** [comment]
Maybe you're right it's also a fresh install of bower. I'll try to investigate...

**Comment by icfantv** [comment]
@adamotte, it's quite possible that a version of UIBS THAT old will not work with angular 1.5.  YMMV, but  please know that we are not going to support any issues that arise.

I'm going to close this until you can show that there is a bug here on our end as the issues forum is not for support requests.
