### ISSUE TITLE
Problem with bower installing the latest version

### ISSUE THREAD

**Issue by immortalcy** [angular-ui/bootstrap-bower#70]
I have noticed that I've been using angular-boostrap 0.14.3 on a project and when I tired to find out the reason I couldn't.

My bower json is as follows:

```
{
  "name": "app",
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "",
    "components-font-awesome": "",
    "ionicons": "",
    "angular": "^1.4.0",
    "angular-animate": "^1.4.0",
    "angular-aria": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-messages": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0",
    "angular-fullscreen": "",
    "angular-bootstrap": "",
    "angular-file-saver": "",
    "angular-strap": "",
    "angular-utils-ui-breadcrumbs": "",
    "api-check": "",
    "angular-formly": "",
    "angular-formly-templates-bootstrap": "",
    "datatables.net": "",
    "datatables.net-bs": "",
    "datatables.net-buttons": "",
    "datatables.net-buttons-bs": "",
    "angular-datatables": "",
    "angular-ui-grid": "",
    "angular-ui-mask": "",
    "ui-router": "0.2.15",
    "angular-ui-select": "",
    "angular-ui-router-tabs": "",
    "international-phone-number": "",
    "ngCountrySelectJs": "",
    "ng-currency": "",
    "lodash": "",
    "angular-wizard": "",
    "satellizer": "",
    "ngprogress": "",
    "angular-ui-notification": "",
    "material-design-iconic-font": "1.0",
    "dropzone": "",
    "angular-ladda": "",
    "angular-loading-spinner": "",
    "ng-slide-down": "",
    "angular-flippy": "",
    "angular-print": "",
    "angular-base64-upload": ""
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    },
    "ngprogress": {
      "main": [
        "build/ngprogress.js",
        "ngProgress.css"
      ]
    },
    "country-select-js": {
      "main": [
        "build/js/countrySelect.min.js",
        "build/css/countrySelect.min.css"
      ]
    },
    "datatables": {
      "main": []
    },
    "material-design-iconic-font": {
      "main": [
        "css/material-design-iconic-font.min.css"
      ]
    }
  },
  "resolutions": {
    "angular": "^1.4.0"
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0"
  },
  "appPath": "app",
  "moduleName": "app"
}

```
Using bower install or bower update the version of angular-boostrap that gets installed is 0.14.3. When I tried to install version 1.3.2 explicitly I got the following error:

`bower         ECONFLICT Unable to find suitable version for angular-bootstrap`

Am I missing something here?

**Comment by wesleycho** [comment]
You have dependencies with conflicting versions of UI Bootstrap specified.

Closing as a usage issue

**Comment by immortalcy** [comment]
Yes I am aware that there is something wrong. But from what I have read on the dependencies the project meets all the requirements. 

Is there a way to find out the conflicts?

**Comment by wesleycho** [comment]
GitHub issues are specifically **not** a support venue - it is your responsibility to investigate each package for the conflict.

**Comment by immortalcy** [comment]
I totally understand what you are saying, but its only this package that says it depends on X and I see that I meet all the requirements that is why I posted here and because I wasn't able to figure out what is going on. What you suggest then is find the problem through trial and error?

Sorry if this approach was wrong - it was clearly not my intention.

**Comment by immortalcy** [comment]
I found out that `angular-ui-router-tabs` was causing the problem and the reason is this line:
`"angular-bootstrap": "^0.14.0"`

Posting here just in case someone else is struggling.

**Comment by rpocklin** [comment]
FWIW **master** of `angular-ui-router-tabs` requires `0.14.0` but you haven't locked down most of your bower dependencies, which can be a recipe for disaster.  If `angular-ui-router-tabs` is the issue, specifying `1.7.0` will solve your problem.  I agree with @wesleycho and @immortalcy this isn't a angular-ui issue at all, please take up further issues elsewhere.

**Comment by immortalcy** [comment]
Thanks for pointing out about bower dependencies, I thought about locking down everything as well as soon as the project was released (v1) but since you are mentioning it I will do it from now. 

Anyhow, specifying version `1.6.0` for `angular-ui-router-tabs` still gives the error `ECONFLICT Unable to find suitable version for angular-bootstrap`.

I am a bit confused here though. Isn't the `caret ^` symbol that is keeping angular-boostrap to be on v0.14.3 since is the latest major release before 1.x.x ?
