### ISSUE TITLE
tooltip positioning issue

### ISSUE THREAD

**Issue by LorenzoCoronati** [angular-ui/bootstrap-bower#72]
The function positionElements does not check wether the targetElemPos.left value is negative and therefore the tooltip gets positioned outside the left margin.
The line
`targetElemPos.left = Math.round(targetElemPos.left);`
IMO should be changed to
`targetElemPos.left = ((targetElemPos.left < 0) ? 0 : Math.round(targetElemPos.left));`

**Comment by pkozlowski-opensource** [comment]
* this repository is only for bower distribution, code and issues live in https://github.com/angular-ui/bootstrap - please re-open there
* while opening issues please follow issue template (most importantly, add a live reproduce scenario) - see https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug
